version: "3.7"

services:
  redis:
    image: redis
    container_name: bitgouel-redis
    hostname: bitgouel-redis
    ports:
      - "6379:6379"
  prometheus:
    image: prom/prometheus:latest
    container_name: bitgouel-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./env/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: "$UID:$GID"
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-data:/var/lib/grafana
    depends_on:
      - prometheus