server:
  port: ${SERVER_PORT:8080}

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000

  datasource:
    url: jdbc:mysql://${DB_URL:localhost:3306}/${DB_NAME:bitgouel}?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:Esperer123!}
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME:bitgoeul06}
    password: ${GMAIL_PASSWORD:aaaabbbbccccdddd}
    url: ${BASE_URL:http://localhost:8080}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

jwt:
  accessSecret: ${JWT_ACCESS:bXNnbXNnbXNnbXNnbXNnbXNnbXNnbXNnbXNn}
  refreshSecret: ${JWT_REFRESH:Yml0Z291ZWw=Yml0Z291ZWw=Yml0Z291ZWw=}
  accessExpiration: ${ACCESS_EXP:1800}
  refreshExpiration: ${REFRESH_EXP:108000}