server:
  port: ${SERVER_PORT:8080}

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    properties:
      hibernate:
        default_batch_fetch_size: 1000

  datasource:
    url: jdbc:mysql://${DB_URL:localhost:3306}/${DB_NAME:bitgouel}?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:Esperer123!}
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}

jwt:
  accessSecret: ${JWT_ACCESS:Yml0Z291ZWwtYWNjZXNzU2VjcmV0}
  refreshSecret: ${JWT_REFRESH:Yml0Z291ZWwtcmVmcmVzaFNlY3JldA==}
  accessExp: ${ACCESS_EXP:1800}
  refreshExp: ${REFRESH_EXP:7200}