name: Bitgouel Server CD

on:
  push:
    branches: [ master ]

env:
  S3_BUCKET_NAME: bitgouel-deploy-bucket
  PROJECT_NAME: Bitgouel_Server

jobs:
  build:
    name: CD
    runs-on: ubuntu-latest
    steps:

      - name: Start Redis
        uses: supercharge/redis-github-action@1.4.0
        with:
          redis-version: 7
          redis-port: 6379

      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Create application.yml on dev
        run: |
          touch ./bitgouel-api/src/main/resources/application.yml
          echo "${{ secrets.BITGOUEL_DEFAULT_ENV }}" > ./bitgouel-api/src/main/resources/application.yml
          echo "${{ secrets.BITGOUEL_PROD_ENV }}" > ./bitgouel-api/src/main/resources/application-prod.yml
        shell: bash

      - name: Build with Gradle
        run: ./gradlew clean bitgouel-api:build -i
        shell: bash

      - name: Make zip file
        run: zip -r ./$GITHUB_SHA.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$S3_BUCKET_NAME/$PROJECT_NAME/$GITHUB_SHA.zip

      - name: Deploy
        run: |
          aws deploy create-deployment \
          --application-name bitgouel-codedeploy \
          --deployment-config-name CodeDeployDefault.OneAtATime \
          --deployment-group-name bitgouel-deploy-group \
          --file-exists-behavior OVERWRITE \
          --s3-location bucket=bitgouel-deploy-bucket,bundleType=zip,key=Bitgouel_Server/$GITHUB_SHA.zip \
          --region ap-northeast-2 \
